# Ansible
ANSIBLE_HOME=${HOME}/.local/share/ansible
ANSIBLE_CONFIG=${HOME}/.config/ansible/ansible.cfg
# Docker
DOCKER_CONFIG=${HOME}/.config/docker
# Gradle
GRADLE_USER_HOME=${HOME}/.local/share/gradle
# ML & IA
CUDA_CACHE_PATH=${HOME}/.cache/nv
__GL_SHADER_DISK_CACHE_PATH=${HOME}/.cache/nv
# NPM (Configuration initiale)
NPM_CONFIG_USERCONFIG=${HOME}/.config/npm/npmrc
# .dotnet (SDK .NET)
DOTNET_CLI_HOME=${HOME}/.local/share/dotnet
