# SHELL config
setopt appendhistory          # Immediately append history instead of overwriting
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_all_dups   # If a new command is a duplicate, remove the older one
setopt autocd                 # if only directory path is entered, cd there.
setopt inc_append_history     # save commands are added to the history immediately, otherwise only when shell exits.
HISTFILE=$HOME/.zhistory
HISTSIZE=10000000
SAVEHIST=10000000

export XDG_CONFIG_HOME=$HOME/.config

# Replace OMZ theme by Maia prompt for login shell (TTY)
if [[ "$(basename "$(cat "/proc/$PPID/comm")")" == "login" ]]; then
  # enable substitution for prompt
  setopt prompt_subst
  # Maia prompt
  PROMPT="%B%{$fg[cyan]%}%(4~|%-1~/.../%2~|%~)%u%b %(!.%F{red}.%F{cyan})%n%f@%F{yellow}%m%f%(!.%F{red}.)%f >%{$fg[cyan]%}>%B%(?.%{$fg[cyan]%}.%{$fg[red]%})>%{$reset_color%}%b"
  RPROMPT="%{$fg[red]%} %(?..[%?])"
else
  ZSH_THEME="${theme}"
fi

export ZSH=/usr/share/oh-my-zsh
export ZSH_CUSTOM=$ZSH/custom

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# set variable before loading its plugin
ZSH_AUTOSUGGEST_USE_ASYNC=1

# Which plugins would you like to load? (plugins can be found in $HOME/.oh-my-zsh/plugins/*)
# Custom plugins may be added to $HOME/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=( ${plugins} )

# Use user cache directory
export ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if ! [ -d $ZSH_CACHE_DIR ]; then
  mkdir $ZSH_CACHE_DIR
fi

# SSH agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR"/ssh-agent.socket
if [[ -f /usr/bin/ksshaskpass ]]; then
  export SSH_ASKPASS=/usr/bin/ksshaskpass
  # Workaround hide print without `SSH_ASKPASS_REQUIRE=prefer`
  zstyle :omz:plugins:ssh-agent helper "$(basename $SSH_ASKPASS)"
fi
zstyle :omz:plugins:ssh-agent lifetime 24h
zstyle :omz:plugins:ssh-agent quiet yes

# Enable Powerlevel10k instant prompt. Should stay close to the top of $HOME/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Encoding stuff for the terminal if ~/.zshenv doesn't exist
[[ ! -f ~/.zshenv ]] && export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$HOME/.asdf/shims:$PATH"

source $ZSH/oh-my-zsh.sh

# Default fzf options
export FZF_DEFAULT_OPTS="--height 80%"
# Add tree preview on ALT+C shortcut
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200' --reverse"

# Load shared function and aliases
SHARE_DIR=/usr/share/personal-env
source $SHARE_DIR/functions.sh
source $SHARE_DIR/aliases.sh

# Store your own aliases in the $HOME/.aliases file and load the here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Load autocomplete
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
[[ -f /usr/local/bin/mc ]] && complete -o nospace -C /usr/local/bin/mc mc
[[ -f /usr/bin/cmctl ]] && source <(cmctl completion zsh) && compdef _cmctl cmctl
[[ -f /usr/bin/velero ]] && source <(velero completion zsh) && compdef _velero velero
[[ -f /usr/bin/vault ]] && complete -o nospace -C /usr/bin/vault vault
