[settings]
idiomatic_version_file_enable_tools = ["python", "node"]

# Trust mise config in Developpement directory
trusted_config_paths = [
    '~/Development/*',
]

env_file = '.env'
experimental = true

[tools]
chezmoi = "2.72.1"
flux2 = "2.9.5"
"github:alltuner/mise-completions-sync" = "latest"
helm = "4.3.0"
kubectl = "1.37.0"
pi = "0.85.1"
shellcheck = "0.11.0"
uv = "0.12.13"

[hooks]
postinstall = "misecompsync --shell zsh"
